version: "3"
services:
  solr:
    build:
      dockerfile: ./solr/Dockerfile
    container_name: sandboxf-cudl-solr
    ports:
      - 8983:8983
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    volumes:
      - ./data/solr:/var/solr