version: "3"
services:
  solr:
    build:
      dockerfile: ./solr/Dockerfile
    container_name: cdcp-solr
    ports:
      - 8983:8983 # Do not expose port
    #command:
    #  - solr-precreate
    #  - core
    networks:
      - solr_net

networks:
  solr_net:
