services:
  solr:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: darwin-solr
    ports:
      - 8983:8983
    environment:
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
    volumes:
      - ./external-vol:/var/solr
